# Chunks

[Elegant, flexible, and fast dynamic report generation with R](https://yihui.org/knitr/)

El paquete `knitr` proporciona muchas opciones de **fragmentos de código** `chunk` para personalizar casi todos los componentes de los chunks, como el código fuente, la salida de texto, los gráficos (tamaño, resolución, salida) y el idioma del fragmento. 

Se puede insertar un fragmento de código `chunk` en R utilizando la barra de herramientas de RStudio `Code -> Insert Chunk` o el método abreviado `Ctrl + Alt + I`.  


Se tiene un control preciso sobre todos los resultados a través de las opciones dentro de los chunk, que se pueden proporcionar dentro de las llaves (```` ```{r```` y `}`)). Por ejemplo, se puede elegir ocultar la salida de texto a través de la opción `results = 'hide'` dentro del chunk o establecer la altura de la figura en 4 pulgadas a través de `fig.height = 4`. Las opciones de fragmentos están separadas por comas, por ejemplo,    

````markdown
`r ''````{r, chunk-label, results='hide', fig.height=4}
````

Hay una gran cantidad de opciones de chunks en `knitr` documentadas en https://yihui.name/knitr/options . 
Un subconjunto de ellos se muestran a continuación:    

- `eval`: Ya sea para evaluar un fragmento de código | `eval = TRUE` o  `eval = FALSE`.    
- `echo`: Si se desea mostrar el código de R en el documento de salida (es posible que alguien no prefiera leer el código sino solo los resultados o imágenes)  | `echo = TRUE` o `echo = FALSE`.     
- `results`: cuando se establece en `results = 'hide'`, la salida de texto se ocultará;       
+ Cuando se establece en `results = 'asis'`la salida de texto es tal cual, es decir, los resultados del texto se muestran sin formato directamente en el documento de salida  sin formato desde el código R.       

````markdown
`r ''````{r, results='asis'}
cat("I'm raw **Markdown** content.\n")
```
````
 
+ `results = 'markup'`.    
+ `results = 'asis'`.    
+ `results = 'hold'`.    

- `colapse`:  Sirve para fusionar la salida de texto y el código fuente en un solo bloque de código en la salida. Esto es principalmente cosmético: `collapse = TRUE` hace que la salida sea más compacta, ya que el código fuente de R y su salida de texto se muestran en un solo bloque de salida. El valor predeterminado `collapse = FALSE` significa que las expresiones R y su salida de texto se separan en diferentes bloques.    


- `warning`, `message` y `error`: Muestra las advertencias, mensajes y errores en el documento de salida. Si se tiene en cuenta que si establece `error = FALSE`, el documento de salida se detendrá ante un error en un fragmento de código y el error se mostrará en la consola R. Del mismo modo, cuando `warning = FALSE` o `message = FALSE`, estos mensajes se mostrarán en la consola R. Siempre es preferible que no se muestren errores en la salida del RMarkdown.    


- `include`: Si se debe incluir algo de un fragmento de código en el documento de salida. Cuando `include = FALSE`, **todo** el chunk se excluye en la salida, pero teniendo en cuenta que aún se evaluará si se pone la opción `eval = TRUE`. Cuando se establecen las opciones:  `echo = FALSE`, `results = 'hide'`, `warning = FALSE` y  `message = FALSE`, es probable que simplemente se refiera a **una sola opción** `include = FALSE` en lugar de suprimir diferentes tipos de salida de texto individualmente.   

- `cache`: Se usa para habilitar el almacenamiento en caché. Si el almacenamiento en caché está habilitado `cache = TRUE`, el mismo fragmento de código no se evaluará la próxima vez que se compile el documento (si no se modificó el fragmento de código), lo que puede ahorrar tiempo. Dependiendo del código que se esté trabajando, conviene a veces habilitarlo para ahorrar tiempo.    


- `fig.width` y `fig.height`: El tamaño de salida del gráfico en R se representa en pulgadas.También se puede especificar las dos opciones juntas en una sola opción `fig.dim`, por ejemplo, los `fig.dim = c(6, 4)` o bien  `fig.width = 6` y `fig.height = 4`. 

- `out.width` y `out.height`: El tamaño de salida de las gráficas R en el documento de salida. Estas opciones pueden escalar las imágenes / fotos  / gráficos. Se puede usar en porcentajes, por ejemplo, `out.width = '80%'` significa 80% del ancho de la página.    

- fig.align: La alineación de los gráficos. Pueden ser `'left'`, `'center'` o `'right'`.        

- `fig.cap`:  El pie de figura, por ejemplo, `fig.cap = 'Este es el pie del gráfico'`.    


## Setup  

Si una determinada opción debe configurarse con frecuencia en un varios chunks de todo el código, se puede considerar configurarla globalmente en el primer fragmento de código del RMarkdonwn que siempre aparece por default, por ejemplo:   

````markdown
`r ''````{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8, collapse = TRUE, echo = TRUE, eval = TRUE, fig.align = 'center')
```
````  

Además de fragmentos de código `chunk`, también puede insertar valores de objetos de R en líneas dentro del texto. Por ejemplo: 

````markdown
`r ''````{r}
x = 5  # radius of a circle
```

For a circle with the radius `r '\x60r x\x60'`,
its area is `r '\x60r pi * x^2\x60'`.
````




